name: Build latest (Flatpak)
# trigger via either push to selected branches or on manual run
on:
  #push:
 #   branches:
 #     - main
 #     - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-flatpak
  cancel-in-progress: true

jobs:
  build_x64:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - uses: actions/checkout@v5
      - name: Compiles flatpak
        run: |
          flatpak-builder --repo=CCrepo --install-deps-from=flathub --arch=x86_64 build/flatpak misc/flatpak/net.classicube.flatpak.client.X11.json
          flatpak build-bundle CCrepo --arch=x86_64 CC-x64.flatpak net.classicube.flatpak.client

          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'CC-x64.flatpak'
          DEST_NAME: 'net.classicube.client.flatpak-x86_64.flatpak'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce x86_64 flatpak'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'

  build_arm64:
    timeout-minutes: 10
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
    - uses: actions/checkout@v5
      - name: Compiles flatpak
        run: |
          flatpak-builder --repo=CCrepo --install-deps-from=flathub --arch=aarch64 build/flatpak misc/flatpak/net.classicube.flatpak.client.X11.json
          flatpak build-bundle CCrepo --arch=aarch64 CC-arm64.flatpak net.classicube.flatpak.client

          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'CC-arm64.flatpak'
          DEST_NAME: 'net.classicube.client.flatpak-aarch64.flatpak'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce aarch64 flatpak'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
